@extends('layouts.app')
@section('content')
    @include('component.intro-shop-slide')
    <div id="all-container" class="p-3">
        @include('component.product.best-seller-products')
        @include('component.product.latest-products')
        @include('component.product.commended-products')
    </div>
@endsection
@section('script')
    <script type="text/javascript">
        $('.owl-carousel').owlCarousel({
            loop:true,
            margin:0,
            nav:true,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:2
                },
                1000:{
                    items:3
                }
            }
        })
    </script>
@endsection
